// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbvrarfksqsdtcfkjhpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxidnJhcmZrc3FzZHRjZmtqaHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NDQ4MDQsImV4cCI6MjA1NzQyMDgwNH0.tGYhSBoHlrCC6Yz_ObRikrPE7SRlzNRebisNg-0dSyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);